### ISSUE TITLE
About data preprocessing

### ISSUE THREAD

**Issue by code-yuan-shi** [ojwalch/sleep_classifiers#14]
Dear ojwalch
      I'm a Python beginners, your code is too complex to understand for me, I don't know how you preprocessing your data, In my before study, them only is a line feature for a label, I don't have any experience on this  time series data, I'm puzzled how you can make HR and motion data to correlate with sleep labels, Looking for your reply.

**Comment by ojwalch** [comment]
Hi code-yuan-shi,

I've update the README to explain a little better. For the labeled sleep .txt files, the first number is the seconds since the start of the PSG and the second number is the sleep stage. 

Hope this helps,

Olivia
