### ISSUE TITLE
Should the motion data be rearranged?

### ISSUE THREAD

**Issue by wenh06** [ojwalch/sleep_classifiers#2]
The first ''column'', which recorded the measured time, of these data has negative `diff` values. Should they be sorted by this ''column'' when using?

**Comment by ojwalch** [comment]
Yes. Right now, that should happen in the remove_repeats function in utils.py. If you’re using the data for your own purposes, you want to sort by timestamp.

**Comment by wenh06** [comment]
The dominant `diff` in measured time is 20ms, so I guess the sampling frequency of the triaxial accelerometer of these apple watches are 50Hz. Most other values in `diff` in measured time should have been affected by other tasks when using the watches, I believe. As for large gaps of time, either negative or positive, I guess the user synchronized time of its watch with some internet server? Or other possibilities?

**Comment by ojwalch** [comment]
The 50 Hz was set by me-- you can sample motion from the Apple Watch
accelerometer at different rates (see the ojwalch/sleep_accel repo). Any
gaps much larger than that were caused by issues on the server end with
writing the data to file (acceleration was sent to the server in real time
as it was collected), so you'll want to exclude those epochs from
consideration.

**Comment by wenh06** [comment]
I suggest you leave two columns for `time`, one `measure_time` which means the time the value was measured, one `create_time` which means the time the value was written into the database. You can gather data into one row, every n second(s). I hope that you can fetch the `measure_time` directly from the apple watch, which should be created by the device itself. I hope this would help. 
By the way, I named your dataset as `sleep_accel` without knowing the existence of your `sleep_accel` repository. You could consider making it the official short name of your dataset?

**Comment by ojwalch** [comment]
The time stamp is already measure_time: it’s the UNIX time corresponding to the acceleration sample, taken from the Apple Watch. 

>
