### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by balandongiv** [ojwalch/sleep_classifiers#5]
Great works Olivia.
I would like to replicate the result from the paper you co-authored. However, Python compiler returned an error
`FileNotFoundError`

Apparently, this error due to insufficient motion data from the data set downloaded from this [link](https://physionet.org/content/sleep-accel/1.0.0/)

Specifically, the following ids are missing from the motion folder.

>  9961348 , 8258170, 9106476, 8686948, 8530312,, 9618981,  8692923, 844359

May I know whether this deliberate or due to unforeseen error?

Appreciate the time taken entertaining this thread

**Comment by ojwalch** [comment]
Hi: Are you sure you downloaded all the files? When I go to the PhysioNet link, I see all of those IDs in the motion/ folder.

**Comment by balandongiv** [comment]
Yes, my bad. Apparently there is incomplete transfer from my side. Thanks
