### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by sihanlu123** [ojwalch/sleep_classifiers#6]
Hi,Olivia!
I did not find the file named "AppleWatchSubjects".Is it necessary?Where can I find it ?
And I am confused about the code. Your code is very useful but I am pretty new to writing code. Could you tell me which file I need to run in the folder? Is it archive? What files do I need to modify?
I will be very grateful if you could help me.

**Comment by ojwalch** [comment]
Hi bitlsh, sorry it took a year to get back to you. I'm not sure which file you're talking about. I've expanded the README, so hopefully that will help!
