### ISSUE TITLE
_clock_proxy.txt file not found

### ISSUE THREAD

**Issue by Sylvie-sql** [ojwalch/sleep_classifiers#7]
Hi Olivia! Sorry to bother you again.
I was running preprocessing_runner.py and ran into data_plot_builder.py,  in row 73, I found I don't have the "_clock_proxy.txt" file so that the DataPlotBuilder is not plotting any figures. I'm working on validating your paper, but I'm quite new on  python, so I'm experiencing many problems.
![image](https://user-images.githubusercontent.com/56949038/100095068-ebbcf980-2e94-11eb-8a6e-7e1f22a1b8d6.png)

In addition, when I tried to replace ActivityCountService.build_activity_counts() with ActivityCountService.build_activity_counts_without_matlab(subject, data), I don't know what argument I should input for "data". (I don't know how to change the path for my matlab so I'm trying to use the python without matlab)
![image](https://user-images.githubusercontent.com/56949038/100095031-de077400-2e94-11eb-93e8-a34a09587c1a.png)

when I was running analysis_runner.py, pycharm told me "3509524_circadian_feature.out" file not found. I went back to check and found in the folder "C:\Users\SSSyy\PycharmProjects\sleep_classifiers\outputs\features" I don't have files for circadian except  cosine/count/hr/psg/time_feature.out these four type of files.
![image](https://user-images.githubusercontent.com/56949038/100094963-c7f9b380-2e94-11eb-87d6-0427cfe8a17c.png)

Thank you in advance!
Best,
Yue

**Comment by ojwalch** [comment]
Hi Yue,

Right now, there's no way to generate the full circadian features without MATLAB, though you should be able to replace the circadian feature with the cosine feature and get very similar performance. The data you want to pass into build_activity_counts_without_matlab is the MotionCollection data, a.k.a. the raw acceleration data that's on PhysioNet, but you don't need that function to generate the circadian or cosine features. 

Hope this helps, and good luck!

Olivia
