### ISSUE TITLE
Issue getting figures

### ISSUE THREAD

**Issue by tdavidmcc** [ojwalch/sleep_classifiers#8]
Hello I am able to run preprocessing_runner.py, but when running analysis_runner.py to generate the figures I get a runtime error from the classifier_service.py run_in_parallel method in regards to the use of pool. It says: 
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

Please lmk if this is something easily fixed.

**Comment by WilliamAllenTalia** [comment]
I am having the same issue as tdavidmcc above.  
I'm on a 8 core, 16 logical processor Windows 10 machine.

Here is the full error dump............
[FIRST.txt](https://github.com/ojwalch/sleep_classifiers/files/6046311/FIRST.txt)

**Comment by WilliamAllenTalia** [comment]
This problem is that Windows Python reloads the main module each time.
Prevent this be inserting the following line in analysis_runner.py
if __name__ == '__main__':    
before the line:
    start_time = time.time()

**Comment by ojwalch** [comment]
Yes, thank you for catching this! I've updated the main code to include `if name == '__main__'`
